name: CD Pipeline

on:
  workflow_run:
    workflows: ["CD Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull nikin2204/cicd-pipeline:latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 433:8080 --name cicd-pipeline-container nikin2204/cicd-pipeline